In [ ]:
'''
Lower casing
Word Tokenization
sentence tokenization
stopwords
stemming
lemmetization'''

In [182]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hcl\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hcl\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hcl\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [117]:
df = pd.read_csv("sample.csv")

In [118]:
df.head()

tweet_id     author_id  inbound                      created_at  \
0    119237        105834     True  Wed Oct 11 06:55:44 +0000 2017   
1    119238  ChaseSupport    False  Wed Oct 11 13:25:49 +0000 2017   
2    119239        105835     True  Wed Oct 11 13:00:09 +0000 2017   
3    119240  VirginTrains    False  Tue Oct 10 15:16:08 +0000 2017   
4    119241        105836     True  Tue Oct 10 15:17:21 +0000 2017   

                                                text response_tweet_id  \
0  @AppleSupport causing the reply to be disregar...            119236   
1  @105835 Your business means a lot to us. Pleas...               NaN   
2  @76328 I really hope you all change but I'm su...            119238   
3  @105836 LiveChat is online at the moment - htt...            119241   
4  @VirginTrains see attached error message. I've...            119243   

   in_response_to_tweet_id  
0                      NaN  
1                 119239.0  
2                      NaN  
3                 119242.0  
4                 119240.0

In [119]:
df.shape

(93, 7)

In [120]:
df['text'][0]

'@AppleSupport causing the reply to be disregarded and the tapped notification under the keyboard is opened😡😡😡'

In [121]:
'@',"#","^"

('@', '#', '^')

# Lowering

In [122]:
df['text'] = df['text'].str.lower()

In [123]:
df['text'][0]

'@applesupport causing the reply to be disregarded and the tapped notification under the keyboard is opened😡😡😡'

# removing links

In [124]:
df1 = df.copy()

In [125]:
def remove_links(text):
    pattern = r'https?://\S+'
    text_cleaned = re.sub(pattern, "", text)
    return text_cleaned

In [126]:
df1['text'] = df1['text'].apply(remove_links)

In [127]:
df1['text'][1]

'@105835 your business means a lot to us. please dm your name, zip code and additional details about your concern. ^rr '

# Special characters

In [128]:

def remove_symbols(text):
   
    pattern = r'[^\w\s]' 
    
   
    text_cleaned = re.sub(pattern, '', text)
    
    return text_cleaned

In [129]:
df2 = df1.copy()

In [130]:
df2["text"] = df2["text"].apply(remove_symbols)

In [131]:
df2["text"][1]

'105835 your business means a lot to us please dm your name zip code and additional details about your concern rr '

# Removing Numeric values

In [132]:
df3 = df2.copy()

In [133]:
def remove_numbers(text):
    
    pattern = r'\b\d+\b'
    
    
    text_cleaned = re.sub(pattern, '', text)
    
    return text_cleaned

In [134]:
df3["text"] = df3['text'].apply(remove_numbers)

In [135]:
df3["text"][0]

'applesupport causing the reply to be disregarded and the tapped notification under the keyboard is opened'

# Removing emojis

In [136]:
df4 = df3.copy()

In [137]:
def remove_emojis(text):
    
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002500-\U00002BEF"  # chinese char
                               u"\U00002702-\U000027B0"
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u"\U00010000-\U0010ffff"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u200d"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\ufe0f"  # dingbats
                               u"\u3030"
                               "]+", flags=re.UNICODE)
    
   
    text_cleaned = emoji_pattern.sub(r'', text)
    
    return text_cleaned

In [138]:
df4['text'] = df4['text'].apply(remove_emojis)

In [139]:
df4['text'][9]

' thats what were here for miriam   the team should send you an email shortly hp'

# stopwords

In [140]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [141]:
words = nltk.word_tokenize('applesupport causing the reply to be disregarded and the tapped notification under the keyboard is opened')

In [142]:
words

['applesupport',
 'causing',
 'the',
 'reply',
 'to',
 'be',
 'disregarded',
 'and',
 'the',
 'tapped',
 'notification',
 'under',
 'the',
 'keyboard',
 'is',
 'opened']

In [143]:
english_stopwords = set(stopwords.words('english'))
filtered_words = [word for word in words if word.lower() not in english_stopwords]
    

filtered_text = ' '.join(filtered_words)

In [144]:
filtered_words

['applesupport',
 'causing',
 'reply',
 'disregarded',
 'tapped',
 'notification',
 'keyboard',
 'opened']

In [145]:
filtered_text

'applesupport causing reply disregarded tapped notification keyboard opened'

In [146]:
def remove_stopwords(text):
    
    words = nltk.word_tokenize(text)
    
    
    english_stopwords = set(stopwords.words('english'))
    
    
    filtered_words = [word for word in words if word.lower() not in english_stopwords]
    
    
    filtered_text = ' '.join(filtered_words)
    
    return filtered_text

In [147]:
df4['text'] = df4['text'].apply(remove_stopwords)

In [148]:
df4['text'][0]

'applesupport causing reply disregarded tapped notification keyboard opened'

In [149]:
df4['text'][5]

'tried another device miriam mm'

# Stemming

In [150]:
df5 = df4.copy()

In [151]:
def stem_text(text):
    stemmer = PorterStemmer()
    
    words = word_tokenize(text)
    
    stemmed_words = [stemmer.stem(word) for word in words]
    
    stemmed_text = " ".join(stemmed_words)
    
    return stemmed_text
    
    

In [152]:
df5['text'] = df5['text'].apply(stem_text)

In [153]:
df5['text'][0]

'applesupport caus repli disregard tap notif keyboard open'

# Lemmatization

In [154]:
df6 = df4.copy()

In [155]:
def lemmatize_text(text):
    
    lemmetizer = WordNetLemmatizer()
    
    words = word_tokenize(text)
    
    lemmatize_words = [lemmetizer.lemmatize(word) for word in words]
    
    lemmatize_text = " ".join(lemmatize_words)
    
    return lemmatize_text

In [156]:
df6['text'] = df6['text'].apply(lemmatize_text)

In [157]:
df6['text'][0]

'applesupport causing reply disregarded tapped notification keyboard opened'

In [ ]:
'''You  need to do one hot encoding on top of text feature
You need to perform BOW from the text column
Here you can try N-grams also like 2-gram, 3-gram,4-gram
At the end you have to perform the tf-idf 
'''

## Document Matrix(Bow)

In [158]:
df7 = df6.copy()

In [159]:
vectorizer = CountVectorizer()

# Fit the vectorizer to the text data
doc_matrix = vectorizer.fit_transform(df7['text'].tolist())

In [160]:
doc_matrix

<93x506 sparse matrix of type '<class 'numpy.int64'>'
	with 934 stored elements in Compressed Sparse Row format>

In [161]:
vectorizer.vocabulary_

{'applesupport': 34,
 'causing': 77,
 'reply': 359,
 'disregarded': 126,
 'tapped': 435,
 'notification': 296,
 'keyboard': 234,
 'opened': 307,
 'business': 64,
 'mean': 271,
 'lot': 263,
 'please': 327,
 'dm': 128,
 'name': 290,
 'zip': 505,
 'code': 89,
 'additional': 9,
 'detail': 119,
 'concern': 94,
 'rr': 366,
 'really': 347,
 'hope': 198,
 'change': 79,
 'im': 209,
 'sure': 427,
 'wont': 494,
 'dont': 131,
 'livechat': 255,
 'online': 305,
 'moment': 284,
 'contact': 97,
 'option': 310,
 'leave': 245,
 'message': 272,
 'request': 360,
 'call': 70,
 'back': 48,
 'virgintrains': 477,
 'see': 373,
 'attached': 43,
 'error': 140,
 'ive': 225,
 'tried': 459,
 'leaving': 246,
 'voicemail': 479,
 'several': 381,
 'time': 453,
 'past': 320,
 'week': 484,
 'another': 29,
 'device': 120,
 'miriam': 279,
 'mm': 281,
 'yep': 501,
 'laptop': 239,
 'today': 454,
 'different': 122,
 'browser': 62,
 'working': 496,
 'ok': 301,
 'link': 252,
 'help': 191,
 'still': 418,
 'havent': 187,
 'heard'

In [162]:
doc_matrix[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## Bigrams


In [163]:
bigram = CountVectorizer(ngram_range=(2,2))

In [165]:
bigramvocab = bigram.fit_transform(df7['text'].tolist())

In [166]:
bigram.vocabulary_

{'applesupport causing': 44,
 'causing reply': 109,
 'reply disregarded': 536,
 'disregarded tapped': 166,
 'tapped notification': 647,
 'notification keyboard': 453,
 'keyboard opened': 367,
 'business mean': 93,
 'mean lot': 423,
 'lot please': 411,
 'please dm': 496,
 'dm name': 176,
 'name zip': 447,
 'zip code': 782,
 'code additional': 118,
 'additional detail': 8,
 'detail concern': 153,
 'concern rr': 128,
 'really hope': 524,
 'hope change': 307,
 'change im': 111,
 'im sure': 323,
 'sure wont': 637,
 'wont dont': 764,
 'livechat online': 396,
 'online moment': 467,
 'moment contact': 437,
 'contact option': 131,
 'option leave': 472,
 'leave message': 383,
 'message request': 425,
 'request call': 538,
 'call back': 100,
 'virgintrains see': 736,
 'see attached': 552,
 'attached error': 66,
 'error message': 197,
 'message ive': 424,
 'ive tried': 359,
 'tried leaving': 696,
 'leaving voicemail': 384,
 'voicemail several': 740,
 'several time': 565,
 'time past': 685,
 'past 

In [169]:
bigramvocab[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# Trigram

In [170]:
trigram = CountVectorizer(ngram_range=(3,3))

In [171]:
trigramvocab = trigram.fit_transform(df7['text'].tolist())

In [172]:
trigram.vocabulary_

{'applesupport causing reply': 41,
 'causing reply disregarded': 101,
 'reply disregarded tapped': 505,
 'disregarded tapped notification': 155,
 'tapped notification keyboard': 607,
 'notification keyboard opened': 425,
 'business mean lot': 89,
 'mean lot please': 395,
 'lot please dm': 385,
 'please dm name': 468,
 'dm name zip': 166,
 'name zip code': 419,
 'zip code additional': 731,
 'code additional detail': 110,
 'additional detail concern': 6,
 'detail concern rr': 144,
 'really hope change': 495,
 'hope change im': 282,
 'change im sure': 103,
 'im sure wont': 296,
 'sure wont dont': 597,
 'livechat online moment': 371,
 'online moment contact': 438,
 'moment contact option': 409,
 'contact option leave': 121,
 'option leave message': 443,
 'leave message request': 351,
 'message request call': 397,
 'request call back': 506,
 'virgintrains see attached': 687,
 'see attached error': 518,
 'attached error message': 63,
 'error message ive': 184,
 'message ive tried': 396,
 'iv

In [175]:
trigramvocab[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## Mix 

In [176]:
mix = CountVectorizer(ngram_range=(1,2))

In [177]:
mix_vocab = mix.fit_transform(df7['text'].tolist())

In [178]:
mix.vocabulary_

{'applesupport': 78,
 'causing': 186,
 'reply': 894,
 'disregarded': 292,
 'tapped': 1082,
 'notification': 749,
 'keyboard': 601,
 'opened': 776,
 'applesupport causing': 79,
 'causing reply': 187,
 'reply disregarded': 896,
 'disregarded tapped': 293,
 'tapped notification': 1083,
 'notification keyboard': 750,
 'keyboard opened': 602,
 'business': 157,
 'mean': 693,
 'lot': 674,
 'please': 822,
 'dm': 297,
 'name': 735,
 'zip': 1287,
 'code': 207,
 'additional': 17,
 'detail': 272,
 'concern': 221,
 'rr': 910,
 'business mean': 158,
 'mean lot': 695,
 'lot please': 675,
 'please dm': 824,
 'dm name': 305,
 'name zip': 738,
 'zip code': 1288,
 'code additional': 208,
 'additional detail': 18,
 'detail concern': 273,
 'concern rr': 223,
 'really': 871,
 'hope': 505,
 'change': 190,
 'im': 530,
 'sure': 1063,
 'wont': 1258,
 'dont': 316,
 'really hope': 872,
 'hope change': 506,
 'change im': 191,
 'im sure': 533,
 'sure wont': 1065,
 'wont dont': 1259,
 'livechat': 651,
 'online': 772

In [181]:
mix_vocab[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## TF-IDF

In [183]:
tfidf = TfidfVectorizer()

In [184]:
tfidf_vocab = tfidf.fit_transform(df7['text'].tolist())

In [186]:
tfidf.idf_

array([4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 ,
       4.8501476 , 4.44468249, 4.15700042, 4.8501476 , 4.8501476 ,
       4.15700042, 4.8501476 , 4.8501476 , 4.8501476 , 4.15700042,
       4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 ,
       4.8501476 , 4.8501476 , 4.8501476 , 4.15700042, 4.8501476 ,
       4.8501476 , 3.75153531, 4.44468249, 4.8501476 , 4.8501476 ,
       4.44468249, 4.44468249, 3.93385687, 3.93385687, 3.05838813,
       4.8501476 , 3.75153531, 4.8501476 , 4.8501476 , 4.8501476 ,
       4.8501476 , 4.8501476 , 4.44468249, 4.8501476 , 4.8501476 ,
       4.8501476 , 3.75153531, 4.8501476 , 3.59738463, 4.8501476 ,
       3.93385687, 4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 ,
       4.8501476 , 4.8501476 , 4.44468249, 4.8501476 , 4.44468249,
       4.8501476 , 4.44468249, 4.44468249, 4.8501476 , 4.8501476 ,
       4.44468249, 4.8501476 , 4.8501476 , 4.44468249, 4.8501476 ,
       4.15700042, 4.44468249, 4.8501476 , 4.8501476 , 4.85014

In [187]:
tfidf.get_feature_names()

['1065320gac7a8e02',
 '1h',
 '4h',
 '720am',
 '7plus',
 '803am',
 'ac',
 'account',
 'ad',
 'additional',
 'address',
 'adnams',
 'advise',
 'affect',
 'age',
 'ago',
 'agoura',
 'air',
 'aircraft',
 'alcohol',
 'allow',
 'almost',
 'also',
 'always',
 'amanda',
 'amazon',
 'amp',
 'android',
 'anker',
 'another',
 'answer',
 'anything',
 'app',
 'apple',
 'applesupport',
 'appreciate',
 'apps',
 'armv7',
 'article',
 'as',
 'ask',
 'ask_spectrum',
 'assistance',
 'attached',
 'avoid',
 'away',
 'ay',
 'ba8733',
 'back',
 'basket',
 'battery',
 'beatner',
 'beg',
 'behavior',
 'belief',
 'bit',
 'blind',
 'bluetooth',
 'brilliant',
 'british_airways',
 'broadside',
 'broken',
 'browser',
 'bug',
 'business',
 'buying',
 'bye',
 'cable',
 'cache',
 'cachecookies',
 'call',
 'called',
 'calling',
 'care',
 'carry',
 'cause',
 'caused',
 'causing',
 'challenged',
 'change',
 'charge',
 'chat',
 'check',
 'cheer',
 'choice',
 'chris',
 'click',
 'close',
 'coaxial',
 'code',
 'colleague',
